FROM osrf/ros:humble-desktop

RUN apt update && apt install -y \
    python3-pip \
    python3-venv \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    paho-mqtt \
    fastapi \
    uvicorn \
    sqlalchemy \
    websockets \
    numpy

WORKDIR /ros2_ws
COPY ../robot /ros2_ws/src/robot
COPY ../services/fleet-manager/src /ros2_ws/src/fleet-manager

# Собираем пакет (здесь важно, что мы копируем исходники и собираем)
RUN . /opt/ros/humble/setup.sh && colcon build --packages-select amr_hardware

COPY infrastructure/ros-dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]

# RUN apt update && apt install -y ros-humble-gazebo-ros-pkgs